### ISSUE TITLE
[Community] Using powerful graphql dashboard 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/voyager-server#74]
Current graphql dashboard has very prominent ux issues and has really bad user experience. 
https://github.com/imolorhe/altair is quickly gaining popularity in graphql scene and it has much more functionalities.

**Comment by ankitjena** [comment]
@wtrocki  I would like to work on this issue.

**Comment by wtrocki** [comment]
Thank you for letting us know. This issue can be used as way to get started with Voyager. 
There are couple graphql explorers available with different functionalities. I think good start will be to research available explorers and write short blog post on dev.to comparing them. I'm happy to review blog post before publishing. Later we can share post with team and community and pick one that will be the most promising. Integration with voyager should not be problematic and we can get into details at later stage

**Comment by wtrocki** [comment]
From my experience Altair will be the best explorer on the market but there is not much info about general list of alternatives so blog post will guide community into alternatives.

Later stage we can fork this repo and plan tasks for integrating Altair or other solution into Voyager

**Comment by ankitjena** [comment]
Okay I'm working on it.

**Comment by darahayes** [comment]
While the GraphQL Playground has its issues, it does have the advantage of widespread adoption and being included in Apollo by default. Having used Altair in the [showcase app](https://github.com/aerogear/ionic-showcase), we decided to [remove it](https://github.com/aerogear/ionic-showcase/pull/205). Closing this now.
