### ISSUE TITLE
"GET query missing" when NODE_ENV=production

### ISSUE THREAD

**Issue by aliok** [aerogear/voyager-server#92]
Run the basic example from the showcase. But use `NODE_ENV=production`. You will see `GET query missing.` when you open localhost:4000/graphql in the browser.

This is probably a feature that disables playground in production cases, but I want to make sure ...later

**Comment by wtrocki** [comment]
@aliok https://www.apollographql.com/docs/apollo-server/features/graphql-playground.html#Enabling-GraphQL-Playground-in-production

**Comment by wtrocki** [comment]
@aliok Where this happens? Examples? This is typically application misconfiguration rather than voyager-server side issue.

**Comment by aliok** [comment]
I had this in my example app that uses Voyager framework.
But I believe @wojta had it some where else.

Anyway, thx for pointing at the docs @wtrocki . Closing this one
